student_performance_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_DATABASE_PATH', 'dev.duckdb') }}"
      threads: 1
    prod:
      type: duckdb
      path: "{{ env_var('DBT_DATABASE_PATH', 'prod.duckdb') }}"
      threads: 1
